INSERT INTO new_companies_queue (payload) VALUES
            ('{"companyName": "NVIDIA", "ticker": "NVDA"}'),
            ('{"companyName": "Apple", "ticker": "AAPL"}'),
            ('{"companyName": "Alphabet", "ticker": "GOOG"}'),
            ('{"companyName": "Microsoft", "ticker": "MSFT"}'),
            ('{"companyName": "Amazon", "ticker": "AMZN"}'),
            ('{"companyName": "Broadcom", "ticker": "AVGO"}'),
            ('{"companyName": "Meta Platforms", "ticker": "META"}'),
            ('{"companyName": "Tesla", "ticker": "TSLA"}'),
            ('{"companyName": "Oracle", "ticker": "ORCL"}'),
            ('{"companyName": "Netflix", "ticker": "NFLX"}'),
            ('{"companyName": "Micron Technology", "ticker": "MU"}'),
            ('{"companyName": "Palantir Technologies", "ticker": "PLTR"}'),
            ('{"companyName": "Advanced Micro Devices", "ticker": "AMD"}'),
            ('{"companyName": "Cisco Systems", "ticker": "CSCO"}'),
            ('{"companyName": "Applied Materials", "ticker": "AMAT"}'),
            ('{"companyName": "Lam Research", "ticker": "LRCX"}'),
            ('{"companyName": "IBM", "ticker": "IBM"}'),
            ('{"companyName": "Intel", "ticker": "INTC"}'),
            ('{"companyName": "KLA", "ticker": "KLAC"}'),
            ('{"companyName": "Salesforce", "ticker": "CRM"}'),
            ('{"companyName": "Texas Instruments", "ticker": "TXN"}'),
            ('{"companyName": "Analog Devices", "ticker": "ADI"}'),
            ('{"companyName": "Arista Networks", "ticker": "ANET"}'),
            ('{"companyName": "Uber Technologies", "ticker": "UBER"}'),
            ('{"companyName": "QUALCOMM", "ticker": "QCOM"}'),
            ('{"companyName": "Booking Holdings", "ticker": "BKNG"}'),
            ('{"companyName": "Palo Alto Networks", "ticker": "PANW"}'),
            ('{"companyName": "AppLovin", "ticker": "APP"}'),
            ('{"companyName": "Intuit", "ticker": "INTU"}'),
            ('{"companyName": "ServiceNow", "ticker": "NOW"}'),
            ('{"companyName": "Dell Technologies", "ticker": "DELL"}'),
            ('{"companyName": "Adobe", "ticker": "ADBE"}'),
            ('{"companyName": "CrowdStrike", "ticker": "CRWD"}'),
            ('{"companyName": "Equinix", "ticker": "EQIX"}'),
            ('{"companyName": "Sandisk", "ticker": "SNDK"}'),
            ('{"companyName": "Automatic Data Processing", "ticker": "ADP"}'),
            ('{"companyName": "Marvell Technology", "ticker": "MRVL"}'),
            ('{"companyName": "Cadence Design Systems", "ticker": "CDNS"}'),
            ('{"companyName": "Airbnb", "ticker": "ABNB"}'),
            ('{"companyName": "Synopsys", "ticker": "SNPS"}'),
            ('{"companyName": "Cloudflare", "ticker": "NET"}'),
            ('{"companyName": "DoorDash", "ticker": "DASH"}'),
            ('{"companyName": "Fortinet", "ticker": "FTNT"}'),
            ('{"companyName": "Robinhood Markets", "ticker": "HOOD"}'),
            ('{"companyName": "Snowflake", "ticker": "SNOW"}'),
            ('{"companyName": "Electronic Arts", "ticker": "EA"}'),
            ('{"companyName": "Autodesk", "ticker": "ADSK"}'),
            ('{"companyName": "Monolithic Power Systems", "ticker": "MPWR"}'),
            ('{"companyName": "Lumentum Holdings", "ticker": "LITE"}'),
            ('{"companyName": "Keysight Technologies", "ticker": "KEYS"}'),
            ('{"companyName": "Coinbase Global", "ticker": "COIN"}'),
            ('{"companyName": "Strategy", "ticker": "MSTR"}'),
            ('{"companyName": "PayPal", "ticker": "PYPL"}'),
            ('{"companyName": "Coherent", "ticker": "COHR"}'),
            ('{"companyName": "Datadog", "ticker": "DDOG"}'),
            ('{"companyName": "eBay", "ticker": "EBAY"}'),
            ('{"companyName": "Roper Technologies", "ticker": "ROP"}'),
            ('{"companyName": "CoreWeave", "ticker": "CRWV"}'),
            ('{"companyName": "Take-Two Interactive", "ticker": "TTWO"}'),
            ('{"companyName": "Block", "ticker": "XYZ"}'),
            ('{"companyName": "Workday", "ticker": "WDAY"}'),
            ('{"companyName": "Coupang", "ticker": "CPNG"}'),
            ('{"companyName": "Microchip Technology", "ticker": "MCHP"}'),
            ('{"companyName": "Hewlett Packard Enterprise", "ticker": "HPE"}'),
            ('{"companyName": "Fiserv", "ticker": "FISV"}'),
            ('{"companyName": "Veeva Systems", "ticker": "VEEV"}'),
            ('{"companyName": "Symbotic", "ticker": "SYM"}'),
            ('{"companyName": "AST SpaceMobile", "ticker": "ASTS"}'),
            ('{"companyName": "IQVIA", "ticker": "IQV"}'),
            ('{"companyName": "Expedia Group", "ticker": "EXPE"}'),
            ('{"companyName": "Fair Isaac", "ticker": "FICO"}'),
            ('{"companyName": "Fidelity National Information Services", "ticker": "FIS"}'),
            ('{"companyName": "Circle Internet Group", "ticker": "CRCL"}'),
            ('{"companyName": "Reddit", "ticker": "RDDT"}'),
            ('{"companyName": "Zoom Communications", "ticker": "ZM"}'),
            ('{"companyName": "GlobalFoundries", "ticker": "GFS"}'),
            ('{"companyName": "ON Semiconductor", "ticker": "ON"}'),
            ('{"companyName": "Zscaler", "ticker": "ZS"}'),
            ('{"companyName": "NetApp", "ticker": "NTAP"}'),
            ('{"companyName": "Leidos", "ticker": "LDOS"}'),
            ('{"companyName": "SoFi Technologies", "ticker": "SOFI"}'),
            ('{"companyName": "MongoDB", "ticker": "MDB"}'),
            ('{"companyName": "Pure Storage", "ticker": "PSTG"}'),
            ('{"companyName": "Global Payments", "ticker": "GPN"}'),
            ('{"companyName": "Twilio", "ticker": "TWLO"}'),
            ('{"companyName": "Samsara", "ticker": "IOT"}'),
            ('{"companyName": "HP", "ticker": "HPQ"}'),
            ('{"companyName": "CoStar Group", "ticker": "CSGP"}'),
            ('{"companyName": "Astera Labs", "ticker": "ALAB"}'),
            ('{"companyName": "PTC", "ticker": "PTC"}'),
            ('{"companyName": "Entegris", "ticker": "ENTG"}'),
            ('{"companyName": "SS&C Technologies", "ticker": "SSNC"}'),
            ('{"companyName": "Credo Technology", "ticker": "CRDO"}'),
            ('{"companyName": "Akamai Technologies", "ticker": "AKAM"}'),
            ('{"companyName": "F5", "ticker": "FFIV"}'),
            ('{"companyName": "MACOM Technology Solutions", "ticker": "MTSI"}'),
            ('{"companyName": "Toast", "ticker": "TOST"}'),
            ('{"companyName": "Trimble", "ticker": "TRMB"}'),
            ('{"companyName": "Tyler Technologies", "ticker": "TYL"}'),
            ('{"companyName": "Okta", "ticker": "OKTA"}'),
            ('{"companyName": "Amphenol Corp.", "ticker": "APH"}'),
            ('{"companyName": "Corning Inc.", "ticker": "GLW"}'),
            ('{"companyName": "Western Digital Corp.", "ticker": "WDC"}'),
            ('{"companyName": "Motorola Solutions Inc.", "ticker": "MSI"}'),
            ('{"companyName": "Ciena Corp.", "ticker": "CIEN"}'),
            ('{"companyName": "Teradyne Inc.", "ticker": "TER"}'),
            ('{"companyName": "Teledyne Technologies Inc.", "ticker": "TDY"}'),
            ('{"companyName": "Cognizant Technology Solutions Corp.", "ticker": "CTSH"}'),
            ('{"companyName": "Jabil Inc.", "ticker": "JBL"}'),
            ('{"companyName": "VeriSign, Inc.", "ticker": "VRSN"}'),
            ('{"companyName": "MKS Instruments, Inc.", "ticker": "MKSI"}'),
            ('{"companyName": "Advanced Energy Industries, Inc.", "ticker": "AEIS"}'),
            ('{"companyName": "CDW Corp.", "ticker": "CDW"}'),
            ('{"companyName": "TTM Technologies, Inc.", "ticker": "TTMI"}'),
            ('{"companyName": "Lattice Semiconductor Corp.", "ticker": "LSCC"}'),
            ('{"companyName": "Super Micro Computer, Inc.", "ticker": "SMCI"}'),
            ('{"companyName": "TD SYNNEX Corp.", "ticker": "SNX"}'),
            ('{"companyName": "Gen Digital Inc.", "ticker": "GEN"}'),
            ('{"companyName": "Onto Innovation Inc.", "ticker": "ONTO"}'),
            ('{"companyName": "Rambus Inc.", "ticker": "RMBS"}'),
            ('{"companyName": "InterDigital, Inc.", "ticker": "IDCC"}'),
            ('{"companyName": "Sanmina Corp.", "ticker": "SANM"}'),
            ('{"companyName": "Zebra Technologies Corp.", "ticker": "ZBRA"}'),
            ('{"companyName": "Littelfuse, Inc.", "ticker": "LFUS"}'),
            ('{"companyName": "Semtech Corp.", "ticker": "SMTC"}'),
            ('{"companyName": "Viavi Solutions Inc.", "ticker": "VIAV"}'),
            ('{"companyName": "Confluent, Inc.", "ticker": "CFLT"}'),
            ('{"companyName": "GoDaddy Inc.", "ticker": "GDDY"}'),
            ('{"companyName": "Cognex Corp.", "ticker": "CGNX"}'),
            ('{"companyName": "SiTime Corp.", "ticker": "SITM"}'),
            ('{"companyName": "FormFactor, Inc.", "ticker": "FORM"}'),
            ('{"companyName": "Arrow Electronics, Inc.", "ticker": "ARW"}'),
            ('{"companyName": "Dynatrace, Inc.", "ticker": "DT"}'),
            ('{"companyName": "HubSpot, Inc.", "ticker": "HUBS"}'),
            ('{"companyName": "Gartner, Inc.", "ticker": "IT"}'),
            ('{"companyName": "Clearwater Analytics Holdings, Inc.", "ticker": "CWAN"}'),
            ('{"companyName": "Cirrus Logic, Inc.", "ticker": "CRUS"}'),
            ('{"companyName": "Silicon Laboratories Inc.", "ticker": "SLAB"}'),
            ('{"companyName": "Qorvo, Inc.", "ticker": "QRVO"}'),
            ('{"companyName": "Guidewire Software, Inc.", "ticker": "GWRE"}'),
            ('{"companyName": "Amkor Technology, Inc.", "ticker": "AMKR"}'),
            ('{"companyName": "Skyworks Solutions, Inc.", "ticker": "SWKS"}'),
            ('{"companyName": "EPAM Systems, Inc.", "ticker": "EPAM"}'),
            ('{"companyName": "Avnet, Inc.", "ticker": "AVT"}'),
            ('{"companyName": "Manhattan Associates, Inc.", "ticker": "MANH"}'),
            ('{"companyName": "IonQ, Inc.", "ticker": "IONQ"}'),
            ('{"companyName": "DocuSign, Inc.", "ticker": "DOCU"}'),
            ('{"companyName": "Nutanix, Inc.", "ticker": "NTNX"}'),
            ('{"companyName": "Procore Technologies, Inc.", "ticker": "PCOR"}'),
            ('{"companyName": "Viasat, Inc.", "ticker": "VSAT"}'),
            ('{"companyName": "Allegro MicroSystems, Inc.", "ticker": "ALGM"}'),
            ('{"companyName": "Rubrik, Inc.", "ticker": "RBRK"}'),
            ('{"companyName": "Bentley Systems, Incorporated", "ticker": "BSY"}'),
            ('{"companyName": "Dropbox, Inc.", "ticker": "DBX"}'),
            ('{"companyName": "UiPath, Inc.", "ticker": "PATH"}'),
            ('{"companyName": "Universal Display Corp.", "ticker": "OLED"}'),
            ('{"companyName": "ACI Worldwide, Inc.", "ticker": "ACIW"}'),
            ('{"companyName": "SentinelOne, Inc.", "ticker": "S"}'),
            ('{"companyName": "Pegasystems Inc.", "ticker": "PEGA"}'),
            ('{"companyName": "AppFolio, Inc.", "ticker": "APPF"}'),
            ('{"companyName": "BILL Holdings, Inc.", "ticker": "BILL"}'),
            ('{"companyName": "DigitalOcean Holdings, Inc.", "ticker": "DOCN"}'),
            ('{"companyName": "Rigetti Computing, Inc.", "ticker": "RGTI"}'),
            ('{"companyName": "Kulicke and Soffa Industries, Inc.", "ticker": "KLIC"}'),
            ('{"companyName": "Commvault Systems, Inc.", "ticker": "CVLT"}'),
            ('{"companyName": "Unity Software Inc.", "ticker": "U"}'),
            ('{"companyName": "Box, Inc.", "ticker": "BOX"}'),
            ('{"companyName": "Qualys, Inc.", "ticker": "QLYS"}'),
            ('{"companyName": "GitLab Inc.", "ticker": "GTLB"}'),
            ('{"companyName": "Diodes Incorporated", "ticker": "DIOD"}'),
            ('{"companyName": "Impinj, Inc.", "ticker": "PI"}'),
            ('{"companyName": "Synaptics Incorporated", "ticker": "SYNA"}'),
            ('{"companyName": "Zeta Global Holdings Corp.", "ticker": "ZETA"}'),
            ('{"companyName": "Workiva Inc.", "ticker": "WK"}'),
            ('{"companyName": "Q2 Holdings, Inc.", "ticker": "QTWO"}'),
            ('{"companyName": "ACM Research, Inc.", "ticker": "ACMR"}'),
            ('{"companyName": "CCC Intelligent Solutions Holdings Inc.", "ticker": "CCC"}'),
            ('{"companyName": "Power Integrations, Inc.", "ticker": "POWI"}'),
            ('{"companyName": "Teradata Corp.", "ticker": "TDC"}'),
            ('{"companyName": "Fastly, Inc.", "ticker": "FSLY"}'),
            ('{"companyName": "RingCentral, Inc.", "ticker": "RNG"}'),
            ('{"companyName": "Varonis Systems, Inc.", "ticker": "VRNS"}'),
            ('{"companyName": "Axcelis Technologies, Inc.", "ticker": "ACLS"}'),
            ('{"companyName": "Kyndryl Holdings, Inc.", "ticker": "KD"}'),
            ('{"companyName": "Insight Enterprises, Inc.", "ticker": "NSIT"}'),
            ('{"companyName": "Tenable Holdings, Inc.", "ticker": "TENB"}'),
            ('{"companyName": "DXC Technology Co.", "ticker": "DXC"}'),
            ('{"companyName": "Photronics, Inc.", "ticker": "PLAB"}');
